services:
  postgres_test:
    image: postgres:17.6-alpine
    environment:
      POSTGRES_USER: wiki_test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: wiki_test
    ports:
      - "127.0.0.1:15432:5432"
    networks:
      - wiki_test

  redis_test:
    image: redis:8.0-alpine
    ports:
      - "127.0.0.1:16379:6379"
    networks:
      - wiki_test

networks:
  wiki_test:
    driver: bridge
