/* eslint-disable */
// Generated by frontend/scripts/generate-api-types.mjs from openapi/openapi.json.
// Do not edit by hand.

export type components = {
  schemas: {
    AttachmentResponse: {
      checksum: string
      content_type: string
      file_name: string
      id: string
      size_bytes: number
      uploaded_at: string
      uploaded_by: string
    }
    AuditEntryResponse: {
      action: string
      actor_id: string
      created_at: string
      entity_id: string
      entity_type: string
      id: string
    }
    AuditLogResponse: {
      entries: components['schemas']['AuditEntryResponse'][]
    }
    CreateDocumentRequest: {
      content_markdown?: string
      document_type?: string
      parent_id?: string | null
      phase_key?: string | null
      slug?: string | null
      task_key?: string | null
      title: string
    }
    CreateEvidenceRequest: {
      attachment_id?: string | null
      checksum?: string | null
      document_id?: string | null
      evidence_type?: string
      phase_key?: string | null
      space?: string | null
      task_key?: string | null
      title: string
      url?: string | null
    }
    CreateSpaceRequest: {
      description?: string | null
      key: string
      name: string
    }
    CreateTemplateRequest: {
      body_markdown: string
      document_type: string
      name: string
    }
    DocumentListResponse: {
      documents: components['schemas']['DocumentResponse'][]
    }
    DocumentResponse: {
      body_markdown: string
      created_at: string
      created_by: string
      current_revision?: null | components['schemas']['DocumentRevisionResponse']
      document_type: string
      draft_markdown: string
      evidence: components['schemas']['EvidenceResponse'][]
      id: string
      parent_id?: string | null
      phase_keys: string[]
      slug: string
      space_key: string
      status: string
      task_keys: string[]
      title: string
      updated_at: string
      updated_by: string
    }
    DocumentRevisionListResponse: {
      revisions: components['schemas']['DocumentRevisionResponse'][]
    }
    DocumentRevisionResponse: {
      author_id: string
      body_markdown: string
      document_id: string
      id: string
      published_at: string
      summary?: string | null
      title: string
      version: number
    }
    DocumentSummaryResponse: {
      document_type: string
      id: string
      slug: string
      status: string
      title: string
      updated_at: string
    }
    EvidenceListResponse: {
      evidence: components['schemas']['EvidenceResponse'][]
    }
    EvidenceResponse: {
      attachment_id?: string | null
      checksum?: string | null
      created_at: string
      created_by: string
      document_id?: string | null
      evidence_type: string
      id: string
      phase_key?: string | null
      space_key: string
      task_key?: string | null
      title: string
      url?: string | null
    }
    LinkDocumentRequest: {
      document_id: string
    }
    MoveDocumentRequest: {
      parent_id?: string | null
    }
    PhasePageListResponse: {
      phases: components['schemas']['PhasePageResponse'][]
    }
    PhasePageResponse: {
      document_count: number
      documents: components['schemas']['DocumentSummaryResponse'][]
      evidence: components['schemas']['EvidenceResponse'][]
      evidence_count: number
      phase_key: string
      space_key: string
      title?: string | null
    }
    PublishDocumentRequest: {
      summary?: string | null
    }
    SearchResponse: {
      results: components['schemas']['SearchResultResponse'][]
    }
    SearchResultResponse: {
      id: string
      result_type: string
      snippet: string
      space_key: string
      title: string
      updated_at: string
      url: string
    }
    SpaceListResponse: {
      spaces: components['schemas']['SpaceResponse'][]
    }
    SpaceMemberListResponse: {
      members: components['schemas']['SpaceMemberResponse'][]
    }
    SpaceMemberResponse: {
      display_name: string
      email: string
      joined_at: string
      role: string
      user_id: string
    }
    SpaceResponse: {
      created_at: string
      description?: string | null
      document_count: number
      id: string
      key: string
      member_count: number
      name: string
      owner_id: string
      status: string
      updated_at: string
    }
    SpaceTreeNodeResponse: {
      children: components['schemas']['SpaceTreeNodeResponse'][]
      document_type: string
      id: string
      slug: string
      status: string
      title: string
    }
    SpaceTreeResponse: {
      documents: components['schemas']['SpaceTreeNodeResponse'][]
      space_key: string
    }
    TaskPageListResponse: {
      tasks: components['schemas']['TaskPageResponse'][]
    }
    TaskPageResponse: {
      document_count: number
      documents: components['schemas']['DocumentSummaryResponse'][]
      evidence: components['schemas']['EvidenceResponse'][]
      evidence_count: number
      space_key: string
      task_key: string
      title?: string | null
    }
    TemplateListResponse: {
      templates: components['schemas']['TemplateResponse'][]
    }
    TemplateResponse: {
      body_markdown: string
      document_type: string
      id: string
      name: string
    }
    UpdateDocumentDraftRequest: {
      content_markdown: string
      title?: string | null
    }
    UpdateSpaceRequest: {
      description?: string | null
      name?: string | null
    }
    UpsertSpaceMemberRequest: {
      role: string
    }
    WikiAuthResponse: {
      access_token: string
      display_name: string
      email: string
      expires_in: number
      refresh_token: string
      token_type: string
      user_id: string
      username: string
    }
    WikiCreateUserRequest: {
      display_name: string
      email: string
      password: string
      role?: string
      username: string
    }
    WikiLoginRequest: {
      email: string
      password: string
    }
    WikiRefreshRequest: {
      refresh_token: string
    }
    WikiRegisterRequest: {
      email: string
      name?: string | null
      password: string
      username: string
    }
    WikiUpdateUserRequest: {
      active?: boolean | null
      display_name?: string | null
      email?: string | null
      is_system_admin?: boolean | null
      role?: string | null
      username?: string | null
    }
    WikiUserListResponse: {
      users: components['schemas']['WikiUserResponse'][]
    }
    WikiUserResponse: {
      active: boolean
      display_name: string
      email: string
      id: string
      is_system_admin: boolean
      role: string
      username: string
    }
  }
}

export type AttachmentResponse = components['schemas']['AttachmentResponse']
export type AuditEntryResponse = components['schemas']['AuditEntryResponse']
export type AuditLogResponse = components['schemas']['AuditLogResponse']
export type CreateDocumentRequest = components['schemas']['CreateDocumentRequest']
export type CreateEvidenceRequest = components['schemas']['CreateEvidenceRequest']
export type CreateSpaceRequest = components['schemas']['CreateSpaceRequest']
export type CreateTemplateRequest = components['schemas']['CreateTemplateRequest']
export type DocumentListResponse = components['schemas']['DocumentListResponse']
export type DocumentResponse = components['schemas']['DocumentResponse']
export type DocumentRevisionListResponse = components['schemas']['DocumentRevisionListResponse']
export type DocumentRevisionResponse = components['schemas']['DocumentRevisionResponse']
export type DocumentSummaryResponse = components['schemas']['DocumentSummaryResponse']
export type EvidenceListResponse = components['schemas']['EvidenceListResponse']
export type EvidenceResponse = components['schemas']['EvidenceResponse']
export type LinkDocumentRequest = components['schemas']['LinkDocumentRequest']
export type MoveDocumentRequest = components['schemas']['MoveDocumentRequest']
export type PhasePageListResponse = components['schemas']['PhasePageListResponse']
export type PhasePageResponse = components['schemas']['PhasePageResponse']
export type PublishDocumentRequest = components['schemas']['PublishDocumentRequest']
export type SearchResponse = components['schemas']['SearchResponse']
export type SearchResultResponse = components['schemas']['SearchResultResponse']
export type SpaceListResponse = components['schemas']['SpaceListResponse']
export type SpaceMemberListResponse = components['schemas']['SpaceMemberListResponse']
export type SpaceMemberResponse = components['schemas']['SpaceMemberResponse']
export type SpaceResponse = components['schemas']['SpaceResponse']
export type SpaceTreeNodeResponse = components['schemas']['SpaceTreeNodeResponse']
export type SpaceTreeResponse = components['schemas']['SpaceTreeResponse']
export type TaskPageListResponse = components['schemas']['TaskPageListResponse']
export type TaskPageResponse = components['schemas']['TaskPageResponse']
export type TemplateListResponse = components['schemas']['TemplateListResponse']
export type TemplateResponse = components['schemas']['TemplateResponse']
export type UpdateDocumentDraftRequest = components['schemas']['UpdateDocumentDraftRequest']
export type UpdateSpaceRequest = components['schemas']['UpdateSpaceRequest']
export type UpsertSpaceMemberRequest = components['schemas']['UpsertSpaceMemberRequest']
export type WikiAuthResponse = components['schemas']['WikiAuthResponse']
export type WikiCreateUserRequest = components['schemas']['WikiCreateUserRequest']
export type WikiLoginRequest = components['schemas']['WikiLoginRequest']
export type WikiRefreshRequest = components['schemas']['WikiRefreshRequest']
export type WikiRegisterRequest = components['schemas']['WikiRegisterRequest']
export type WikiUpdateUserRequest = components['schemas']['WikiUpdateUserRequest']
export type WikiUserListResponse = components['schemas']['WikiUserListResponse']
export type WikiUserResponse = components['schemas']['WikiUserResponse']
