[package]
name = "infra"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
sdlc-auth-core = { path = "../../../services-base/crates/sdlc-auth-core" }
shared = { path = "../shared" }
domain = { path = "../domain" }
app = { path = "../app" }
async-trait.workspace = true
tokio.workspace = true
chrono.workspace = true
sqlx.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
serial_test = "3.2"
tokio = { workspace = true, features = ["macros", "rt"] }
