[package]
name = "infra"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[features]
default = []
legacy-tracker = [
    "dep:lettre",
    "dep:migration",
    "dep:moka",
    "dep:sea-orm",
    "dep:serde_json",
    "domain/legacy-tracker",
]

[dependencies]
shared = { path = "../shared" }
domain = { path = "../domain" }
app = { path = "../app" }
async-trait.workspace = true
tokio.workspace = true
chrono.workspace = true
lettre = { workspace = true, optional = true }
migration = { path = "../migration", optional = true }
moka = { workspace = true, optional = true }
sea-orm = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
sqlx.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
serial_test = "3.2"
tokio = { workspace = true, features = ["macros", "rt"] }
