// Regenerates the flat-type bridge over openapi-typescript output.
// Kept so 20+ hand-written API modules can import `WikiAuthResponse` directly
// instead of components['schemas']['WikiAuthResponse'].
// Run as part of `pnpm generate:api` (after openapi-typescript itself).
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const frontendRoot = path.resolve(scriptDir, '..')
const genPath = path.join(frontendRoot, 'src', 'api', 'generated.ts')
const outPath = path.join(frontendRoot, 'src', 'api', 'generated-exports.ts')

const gen = readFileSync(genPath, 'utf8')

// Schema names live inside `export interface components { schemas: { ... } }`.
// Parse that block (balanced braces) instead of matching indentation globally,
// which also catches `parameters:` keys inside `paths`.
const start = gen.indexOf('export interface components {')
const schemasStart = gen.indexOf('schemas: {', start)
if (start < 0 || schemasStart < 0) {
  throw new Error('components.schemas block not found — did openapi-typescript run first?')
}
let depth = 0
let schemasEnd = -1
for (let i = schemasStart + 'schemas:'.length; i < gen.length; i++) {
  const ch = gen[i]
  if (ch === '{') depth++
  else if (ch === '}') {
    depth--
    if (depth === 0) {
      schemasEnd = i
      break
    }
  }
}
if (schemasEnd < 0) throw new Error('unbalanced braces in components.schemas')
const block = gen.slice(schemasStart, schemasEnd)
const names = [...block.matchAll(/^ {8}([A-Za-z_]\w*): \{/gm)].map((m) => m[1])

if (names.length === 0) {
  throw new Error('no schemas found in generated.ts — did openapi-typescript run first?')
}

const lines = [
  '/* eslint-disable */',
  '// Generated by scripts/generate-exports.mjs from src/api/generated.ts.',
  '// Do not edit by hand.',
  "import type { components } from './generated'",
  '',
]
for (const n of names) {
  lines.push(`export type ${n} = components['schemas']['${n}']`)
}
writeFileSync(outPath, `${lines.join('\n')}\n`, 'utf8')
console.log(`generated-exports.ts: ${names.length} flat types`)
