[package]
name = "app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
shared = { path = "../shared" }
domain = { path = "../domain" }
serde.workspace = true
chrono.workspace = true
uuid.workspace = true
jsonwebtoken.workspace = true
argon2.workspace = true
rand_core.workspace = true
sha2 = "0.10"
hex = "0.4"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
