[package]
name = "domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
publish = false

[dependencies]
shared = { path = "../shared" }
async-trait = "0.1"
serde.workspace = true
chrono.workspace = true
uuid.workspace = true
serde_json.workspace = true

[dev-dependencies]
serde_json.workspace = true
